version: '3.9'

services:
  db:
    container_name: cassandra-dev
    image: cassandra
    ports:
      - 9042:9042
    env_file: "cassandra.env"
    volumes:
      - ./src/config/cassandra.yml:/etc/cassandra/cassandra.yaml
      - ./src/config/schema:/etc/cassandra/schema
